package myJson;

public class JsonStrings {
	public static final String con = "con";
	public static final String dateTime = "dateTime";
	public static final String ind = "ind";
	public static final String indBid = "indBid";
	public static final String indAsk = "indAsk";
	public static final String conUp = "conUp";
	public static final String conDown = "conDown";
	public static final String indUp = "indUp";
	public static final String indDown = "indDown";
	public static final String basketUp = "basketUp";
	public static final String basketDown = "basketDown";
	public static final String optimiMove = "optimiMove";
	public static final String pesimiMove = "pesimiMove";
	public static final String indBidAskCounter  = "indBidAskCounter";
	public static final String base = "base";
	public static final String options = "options";
	public static final String opAvg = "opAvg";
	public static final String op = "op";
	public static final String conBidAskCounter = "conBidAskCounter";
	public static final String delta = "delta";
	public static final String data = "data";
	public static final String call = "call";
	public static final String put = "put";
	public static final String bid = "bid";
	public static final String ask = "ask";
	public static final String last = "last";
	public static final String theoretic = "theoretic";
	public static final String strike = "strike";
	public static final String expStart = "expStart";
	public static final String indDelta = "indDelta";
	public static final String expData = "expData";
	public static final String exp = "exp";
	public static final String expWeek = "expWeek";
	public static final String expMonth = "expMonth";
	public static final String volume = "volume";
	public static final String weight = "weight";
	public static final String deltaNoBaskets = "deltaNoBaskets";
	public static final String stocks = "stocks";
	public static final String baskets = "baskets";
	public static final String connections = "connections";
	public static final String usedConnections = "usedConnections";
	public static final String connectionsLimit = "connectionsLimit";
	public static final String rando = "rando";
	public static final String open = "open";
	public static final String high = "high";
	public static final String low = "low";
	public static final String tomorrow_future = "tomorrow_future";
	public static final String name = "name";
	public static final String x = "x";
	public static final String y = "y";
	
}
